### ISSUE TITLE
[Bug]: SexLab Creatures are not supported.

### ISSUE THREAD

**Issue by AdeptusXIII** [Monitor221hz/Pandora-Behaviour-Engine-Plus#315]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.3.0 Alfa

### Provide Instructions on Reproducing the Problem

Creatures are not supported. Also, SexLab v163 (full, not beta) is not provided with the necessary dependencies (photo provided). Pandora must provide these dependencies, otherwise FNIS compatibility is out of the question.
![photo_5422416264858560157_y](https://github.com/user-attachments/assets/f07ce309-39c6-46d6-ada2-8a778c84b3cc)

### Provide Relevant Files

[Pandora_OUT+modlist+engine_log.zip](https://github.com/user-attachments/files/17007173/Pandora_OUT%2Bmodlist%2Bengine_log.zip)
My "SexFramework" in "modlist" starts from index 1235 to 1260. Mods have been successfully tested on regular FNIS.
I also added FNIS.esp from the previous version of PBE.

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by AdeptusXIII** [comment]
Version PBH 1.4.2 alfa works fine, but without new mods for the combat system.

**Comment by Aperator** [comment]
Have you tried opening the Sexlab's MCM in the third-person?

**Comment by oren19737373** [comment]
Same thing.

**Comment by Nuascura** [comment]
I'm just going to drop it here that I'm not encountering this issue. As Aperator says, you need to open the MCM in third-person, which is also what that blue "?" highlight text tells you to do. You don't mention having done this check in third-person.

The "FNIS For Users Behaviors Generated" does indeed stay as a question mark, but since it works on my setup, I assume it has to do with Pandora not returning the correct FNIS value for the relevant function call.

The System Requirements section has always been finicky. I wouldn't trust its report unless verified empirically.

**Comment by Monitor221hz** [comment]
I have no idea what I have to do with the Sexlab API to turn that into a green OK, so if anyone wants to put me in touch with someone from SL that knows, that'd be great. But otherwise, creatures should be technically working.

**Comment by Nuascura** [comment]
@Monitor221hz Does Pandora somehow mimic an FNIS script? Because that's how SL does its checks, and I have no idea how it is working without the FNIS.pex.

These calls from the MCM are routed through a SL System script that then waits for return values from the FNIS script. For whatever reason, I can confirm along with someone else that SL receives a value from all but one FNIS papyrus function.

**Comment by Nuascura** [comment]
FYI the specific call that is stuck is line 840 in sslSystemConfig.psc from 1.66b
`FNIS.IsGenerated()`
Only a visual issue. It's a non-issue during actual gameplay.
