### ISSUE TITLE
Pandora v2.3+ doesn't start, when 2.1.5 does.

### ISSUE THREAD

**Issue by Pavukus** [Monitor221hz/Pandora-Behaviour-Engine-Plus#341]
Hi. It is supposedly not a bug. Thank you for your hard work. I didn't found additional dependencyes anywhere. Is there any reason why Pandora beta version doesn't start, when alpha versions does? I already downloaded and tryed most of the versions .net 8 desktop runtimes. Exe file just doesn't start. I use MO2, but even separately it doesn't even start.
Thank you again and I hope there will be any possible reasons.

**Comment by John95ac** [comment]
Hello, for some reason, some users of version SE 1.5.97 cannot open the latest versions regardless of the requirements. In the BWY Discord, while discussing the latest version, a user named 'Shibly' found that by applying the argument

-tesv:


![ModOrganizer_OWKePArAP1](https://github.com/user-attachments/assets/fdf42453-92f4-4a2c-aa31-606c6e0eda76)


With that argument, the program runs, but it is not able to support creatures or FNIS animations, which is bad. I think the colon ':' has something to do with that because I tried it in my game, which was working fine, and of course, it only runs Nemesis; it doesn't support creatures or FNIS. Additionally, it generates an output in a DATA folder instead of where it should place the data, so I don't recommend using the argument. However, it's strange that it works that way.

For my part, since the game in 640 AE works wonderfully, and in the latest version 2.4, the ZAZ +8 equipment works very well. However, not everyone can open the program, even some who have the requirements cannot run the exe from the same mod folder, 'just to see if it opens from the same exe with a mouse click.

**Comment by Pavukus** [comment]
I will use previous version for now. Hope next versions will work xD.
Thanks again. And yes, I can't open the program from any directory. Even when I use argument with adress - it doesn't work. Yet with blank brackets it does.

**Comment by Monitor221hz** [comment]
> some users of version SE 1.5.97 cannot open the latest versions regardless of the requirements.

Pandora is not dependant on the exe version.

> With that argument, the program runs, but it is not able to support creatures or FNIS animations, which is bad. I think the colon ':' has something to do with that because I tried it in my game, which was working fine, and of course, it only runs Nemesis; it doesn't support creatures or FNIS. Additionally, it generates an output in a DATA folder instead of where it should place the data, so I don't recommend using the argument. However, it's strange that it works that way.

Please [read the guide carefully](https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus?tab=readme-ov-file#startup-arguments)  to understand the `-tesv:`. What you suggest doing is a misuse of the command because it forces the engine to set the game directory to a blank path. 

Unless you have multiple skyrim installs or a broken game registry, this argument should not be needed. I suspect the latter is what is causing the issue for the original poster; that's something that needs to be resolved on their end. Browse to `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Bethesda Softworks\Skyrim Special Edition` and make sure the `Installed Path` key exists.

**Comment by Pavukus** [comment]
The trouble exist. Installed path is on it's place and have actual adress. I followed the installation guide carefully with MO2. Alpha versions are running well. Yet with blank -tesv it at least running(I am not stupid enough to try it, I can see that it is not intended to work well.)

**Comment by John95ac** [comment]
Hi, I just wanted to let you know that one of the guys in Discord, who had the problem, managed to solve it with the solution mentioned here, worked for Shibly. We’re still waiting on the other guy to test it out, but he went to sleep. I’ll update once he’s tried it in his game. Thanks, everyone, it’s awesome to see this tool reaching more people!

![imagen_2024-11-01_155533488](https://github.com/user-attachments/assets/b77dcc5d-f349-4688-889c-0543b5e1c596)

**Comment by Pavukus** [comment]
I found a reason. I hadn't fully uninstalled legendary edition of skyrim. Beta versions supposedly refers to an installed path much, so without this particular argument it doesn't worked well. When I deleted path for legendary edition it started to work as usual. This works other way for alpha versions. For people actually using multiple versions just use argument -tesv, or it wouldn't work.

**Comment by John95ac** [comment]
Got it, For those who were having issues, they resolved it by following Monitor221hz's instructions. Here’s what they did:

1. Open **Regedit** and check if the following path exists " You can open it by pressing **Windows + R** and typing `regedit` " :  
   `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Bethesda Softworks\Skyrim Special Edition`.  
   Inside, look for the entry `"Installed Path"`. 

2. If "Installed Path" is missing, just run Skyrim directly from Steam or GOG—not through SKSE. Open it from its official launcher, and this will generate the "Installed Path" entry.

3. After that, you can close the game and launch it again via SKSE, whether from MO2 or Vortex. 

-. If you want, you can skip step 1 and go straight to opening the game from Steam or GOG, without using SKSE, in case you’re having trouble with the program not opening.

It’s a straightforward solution that works well, No need for the `-tesv` argument. Thanks for the quick response, hopefully, this helps others facing the same issue.
