### ISSUE TITLE
[Bug]: Vampire Lord T-Posing

### ISSUE THREAD

**Issue by WylerL** [Monitor221hz/Pandora-Behaviour-Engine-Plus#342]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.4.0 beta

### Provide Instructions on Reproducing the Problem

I downloaded and installed the mod Female Vampire Lords - Animation Replacer(and I had all of the mods requirements and such. It was working, I just didn't like it), and after testing decided it wasn't for me and uninstalled it, running Pandora before and after. Now when I load back in my vampire lord animations are broken, even though I have no mods that are effecting these animations. When I check Pandora's cache there isn't even any mention of vampire lord animations. In fact, even when I have this mod installed Pandora doesn't have any folders that deal with vampire lord animations. My game is acting as if the animations just don't exist anymore. I've tried verifying my file integrity, it doesn't detect that anything is missing. I've tried switching back to Nemesis, nothing is any different. Nemesis also doesn't have any vampire lord related files in it's cache. Pls someone try to help.

I had issues with vampire lord animations in the past and I don't really know what I did to fix them. I managed to clear things up temporarily by installed Humanoid Vampire Lords. I just switched to the newer Vampire Lord Renewed (Vampire Lords Framework) ESL mod and things were working fine until I installed and uninstalled the mod mentioned in the first paragraph.

### Provide Relevant Files

[PandoraOutput.zip](https://github.com/user-attachments/files/17608887/PandoraOutput.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
This is not a Pandora bug. This is caused by residual Vampire Lord behavior files from improper uninstall. If you check in the Female Vampire Lord Animation Replacer download, there are several behavior files that conflict with Pandora/Nemesis/FNIS output.

![image](https://github.com/user-attachments/assets/ba07846a-04a2-4ee0-acf6-7442977d4739)

What's likely is that any vampire related output from either Nemesis or Pandora is being affected by these files that remain in your Data folder. There's nothing that's wrong with the engine itself.

**Comment by Monitor221hz** [comment]
> Sorry to keep bothering you but with this information I have a question. I use MO2, so it shouldn't be possible that the mods files are sticking around somehow. Do you have any idea how that would have happened or where I would be able to find them if that is actually the case?

In the right pane of MO2, there should be a Data tab that shows your virtual folder. Navigate to `meshes/actors/vampirelord` and expand all the folders you see. The modded source of those files should show on the right column. Those are the files that Pandora/Nemesis is "seeing" when it runs and overwriting instead of creating a separate file which would normally go their respective output mods. Delete the vampirelord folder and the problem should go away. For any further help, go to the discussion section.

**Comment by WylerL** [comment]
It wasn't the resolution I was expecting, apparently I had another mod that was messing with things that I never would have discovered. Thanks so much! I'll keep that data tab in mind in future, it's very helpful.
