### ISSUE TITLE
[Bug]: NPCs don't dual wield even if you have two weapons

### ISSUE THREAD

**Issue by SerkelDays** [Monitor221hz/Pandora-Behaviour-Engine-Plus#351]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.4.0-beta

### Provide Instructions on Reproducing the Problem

Give him two weapons that can dual wield but he only wields one weapon

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/user-attachments/files/17676206/Pandora_Output.zip)

It happens that when giving an npc/follower two weapons to dual wield, they only wield the right weapon, which was not the case before.
Try enabling and disabling animations in OAR but neither seems to fix anything.

### Provide Visual Proof (optional)

https://github.com/user-attachments/assets/cf10b1eb-d2ea-49a8-975f-e865bf0a7ecb

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the AnimSet class to include a new property for dual wielding animations and updated the Read and ToString methods to handle this new property.

I also created pull request: https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/pull/352


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
